# Dockerfile
KAFKA_VERSION=2.6.0
SCALA_VERSION=2.13
KAFKA_HOME=/opt/kafka
GLIBC_VERSION=2.31-r0

# versions.sh
MAJOR_VERSION=2
MINOR_VERSION=6

# docker-compose.yml
$KAFKA_ZOOKEEPER_CONNECT
$KAFKA_PORT
$KAFKA_CREATE_TOPICS
$START_TIMEOUT
$KAFKA_CREATE_TOPICS_SEPARATOR
$KAFKA_ADVERTISED_PORT
$KAFKA_LISTENERS
$KAFKA_ADVERTISED_LISTENERS
$KAFKA_BROKER_ID
$BROKER_ID_COMMAND
$KAFKA_LOG_DIRS
$KAFKA_HEAP_OPTS
$HOSTNAME_COMMAND
$PORT_COMMAND
$RACK_COMMAND
$KAFKA_BROKER_RACK
$KAFKA_ADVERTISED_HOST_NAME
$CUSTOM_INIT_SCRIPT


